### PR TITLE
Added support for Razer Cynosa Lite

### PR DESCRIPTION
**Pull request by valinet**
I added support for Razer Cynosa Lite in response to issue #92.

### CODE REVIEW

**Review by sourav-dey — APPROVED** [review]

**Comment by 1kc** [comment]
@valinet, looks good. Have you tested it and it works well? I'll make a new release so others can get support for the Razer Cynosa Lite too.

**Comment by valinet** [comment]
Yeah, as I mentioned in issue #92, seems to work properly, sticks even after a reboot, so saving to on board memory which apparently exists works as well. Configure in macOS, reboot to Windows, setting saved, this scenario works as well. I also unplugged and replugged the keyboard a few times, the setting seems to stick. Out of the modes shown in the list, this keyboard only supports Static, Breathe and Spectrum (which is the default), as it only has the same illumination for all keys, not individually configurable lights per key. The other modes indeed do nothing when clicked, they do not crash the app or anything bad, it is just that the keyboard cannot support them with the hardware it has. The way I implemented the patch was by replicating the logic in openrazer.

Thanks.

**Comment by 1kc** [comment]
sounds good! The settings staying with they keboard is the expected behaviour since the settings are hardware. You just have to set it back to the orignal setting. Will make a new release.

**Comment by valinet** [comment]
> sounds good! The settings staying with they keboard is the expected behaviour since the settings are hardware. You just have to set it back to the orignal setting. Will make a new release.

Seems logical, although I thought that this model does not have on board memory as Razer's Windows software is unable to persist the setting after a reboot (it reverts to cycling all colours until the Razer software starts up). So yeah, Razer has a pretty poor software, they cannot even implement all the features of their own devices.

**Comment by 1kc** [comment]
I think they have given up on Mac support at this point. Razer should really tell people that their keyboards/mice are basically Windows only.

**Pull request merged**
