### PR TITLE
Adding support for BlackWidow V3

### PR DESCRIPTION
**Pull request by koffiebaard**
Adding support for BlackWidow V3. I verified all effects work on my keyboard. Please let me know if there's anything else i need to do.

### CODE REVIEW

**Comment by sofwhy** [comment]
Screen Shot 2021-02-15 at 1 38 00 PM
Hi, 
How can I use the Blackwidow V3 patch? This is what I saw after I opened the new released app. I didn't see the function list there. Is it because my keyboard has not been found? I'm using MAC Big Sur.
Thanks.

**Comment by koffiebaard** [comment]
The PR is still open, it hasn't been merged yet. If you don't want to wait you could clone my fork and run it from there.

**Comment by 1kc** [comment]
Will merge and release later today, I have just been busy

**Comment by 1kc** [comment]
Looks good!

**Comment by 1kc** [comment]
@sofwhy Please give it a go: https://github.com/1kc/razer-macos/releases

**Comment by vmuzikar** [comment]
@1kc Thanks for the release! Unfortunately, doesn't seem to work on Intel-based Macs?
Screenshot 2021-02-16 at 11 08 58
This is MacBook Pro 15" 2018.

**Comment by 1kc** [comment]
@vmuzikar try downloading it again now

**Comment by 1kc** [comment]
@vmuzikar try downloading it again now

**Comment by vmuzikar** [comment]
@1kc Thanks for adding the other binary. I can confirm it works correctly with BlackWidow V3.

**Comment by 1kc** [comment]
Great! One more keyboard supported

**Comment by SusMonke** [comment]
Does this only work for this version of blackwidowq?

**Pull request merged**
