### PR TITLE
add support for naga pro

### PR DESCRIPTION
**Pull request by jvk75**
Adds support for both wired and wireless (2.4GHz dongle) Naga Pro mouse

needs `librazermacos` PR to be merged first before this works.

### CODE REVIEW

**Comment by jvk75** [comment]
As requested in #419

**Comment by jvk75** [comment]
@1kc could you check this? now that the `librazermacos` has the support for Naga Pro

**Comment by 1kc** [comment]
@jvk75 Awesome! Will have a look tomorrow and build it.

**Comment by thetimetraveller** [comment]
Has naga pro the same driver than Naga Left Handed 2020?

**Comment by jvk75** [comment]
Probably just copy paste code in `librazermacos`(add "left" define to same places as the "pro" is).

**Comment by 1kc** [comment]
Built with the latest librazermacos [here](https://github.com/1kc/razer-macos/releases/tag/v0.4.5) @jvk75

**Comment by LJ-03** [comment]
Just wanted to clarify here - the wireless support was only for the 2.4GHz dongle and not Bluetooth? I just tested Bluetooth and it's not working, but I see that 2.4GHz dongle is working! 🙌🏻

**Comment by seathasky** [comment]
Not sure why they say they support it, when half the features arent there, including rgb for side buttons, dpi etc

**Pull request merged**
