### PR TITLE
Support for the New DeathAdder Essential

### PR DESCRIPTION
**Pull request by WrathofthePast**
The new version of the DeathAdder Essential has a different PID... also cleaned up the supported Mice on the readme... PR also created for librazermacos.

### CODE REVIEW

**Comment by WrathofthePast** [comment]
Confirmed Working in #477 ... solves #477 & #472.

**Comment by WrathofthePast** [comment]
Ignore that last commit. I fixed my repositories... that commit is already in #458. My PRs should be cleaner from this point forward.

**Comment by WrathofthePast** [comment]
I separated #458 from this PR.

**Comment by 1kc** [comment]
Awesome! I'll have it look tonight and build it on monterry. Apologies for being a bit busy these days

**Comment by WrathofthePast** [comment]
> Awesome! I'll have it look tonight and build it on monterry. Apologies for being a bit busy these days

@1kc, no worries. There's a dmg available on my repo, if you'd like to skip a step. Also, did you ever check out my PR for Huntsman V2 Analog (#458)? It was already merged on librazermacos, so it's just the PR here that's left.

**Comment by 1kc** [comment]
> > Awesome! I'll have it look tonight and build it on monterry. Apologies for being a bit busy these days
> 
> @1kc, no worries. There's a dmg available on my repo, if you'd like to skip a step. Also, did you ever check out my PR for Huntsman V2 Analog (#458)? It was already merged on librazermacos, so it's just the PR here that's left.

Yep easy, I'll merge that one too along with this one.

**Comment by WrathofthePast** [comment]
> > > Awesome! I'll have it look tonight and build it on monterry. Apologies for being a bit busy these days
> > 
> > 
> > @1kc, no worries. There's a dmg available on my repo, if you'd like to skip a step. Also, did you ever check out my PR for Huntsman V2 Analog (#458)? It was already merged on librazermacos, so it's just the PR here that's left.
> 
> Yep easy, I'll merge that one too along with this one.

I updated the dmg on my repo, so you can test both New DeathAdder Essential and Huntsman V2 Analog at once instead of two dmgs.

**Comment by 1kc** [comment]
@WrathofthePast 
I wouldn't be able to test those devices because I don't own them, but others have confirmed that Huntsman V2 Analog works right?

**Comment by WrathofthePast** [comment]
> @WrathofthePast
> I wouldn't be able to test those devices because I don't own them, but others have confirmed that Huntsman V2 Analog works right?

Yes, I tested it myself.

**Pull request merged**
