### PR TITLE
Cynosa V2

### PR DESCRIPTION
**Pull request by BruskB**
Hello, I might have been able to add Cynosa V2 to the supported devices. Can't test because not able to build exactly but debugging process turned out fine.

### CODE REVIEW

**Comment by BruskB** [comment]
Device ID : 1532:025E

**Comment by 1kc** [comment]
Hi! Have you tested it to work properly?

**Comment by BruskB** [comment]
I am not able to test it, can't build the program.
Can you contact me if it is okay with you, so you can help me to test it.

**Comment by 1kc** [comment]
Could you let me know the issues you are running into? Please post screenshots.

**Comment by BruskB** [comment]
Hey, I tried but it's not working. I looked at openrazer and there is still some files needed to upload to this repository.

**Comment by 1kc** [comment]
How well does it work now?

**Comment by f-stojanovic** [comment]
Will there be merge with master as I am trying Cynosa on my MacOS?

**Comment by 1kc** [comment]
I will compile a test release for you to test it, just want to confirm that it works properly before I merge.

**Comment by f-stojanovic** [comment]
> I will compile a test release for you to test it, just want to confirm that it works properly before I merge.

Great! Thanks. :)

**Comment by 1kc** [comment]
@f-stojanovic https://github.com/1kc/razer-macos/releases/tag/v0.2.7-testing

**Comment by f-stojanovic** [comment]
> @f-stojanovic https://github.com/1kc/razer-macos/releases/tag/v0.2.7-testing
It works! Thanks a lot! 💯

**Comment by 1kc** [comment]
Thanks for testing. Will merge now

**Pull request merged**
