### PR TITLE
Added razer accessory driver from openrazer project

### PR DESCRIPTION
**Pull request by dhobi**
This should add support for the following devices:
- RAZER_NOMMO_CHROMA
- RAZER_NOMMO_PRO
- RAZER_CHROMA_MUG
- RAZER_CHROMA_BASE
- RAZER_CHROMA_HDK
- RAZER_MOUSE_BUNGEE_V3_CHROMA
- RAZER_BASE_STATION_V2_CHROMA

Firefly / Goliath (mousemat), Core (egpu), Kraken Kitty (headphone) have been removed from this file as they are handled elsewhere.

Tested with own RAZER_BASE_STATION_V2_CHROMA

### CODE REVIEW

**Comment by Lathanwalker** [comment]
Will this be merged eventually? I would really love support for my Nommo speakers and base station!

**Comment by 1kc** [comment]
I’ll release this by the end of today, just working right now .🥲

**Comment by Lathanwalker** [comment]
> I’ll release this by the end of today, just working right now .🥲

Thank you so much!

**Comment by billstevenson** [comment]
Awesome! I just bought the Chrome base station today when I noticed support was present in openrazer. Happy to help test once support is checked in!

**Comment by 1kc** [comment]
Amazing work @dhobi! Will release to let others test this,

**Comment by 1kc** [comment]
@billstevenson  @Lathanwalker, let us know how it goes: https://github.com/1kc/razer-macos/releases

**Comment by Lathanwalker** [comment]
> @billstevenson @Lathanwalker, let us know how it goes: https://github.com/1kc/razer-macos/releases

I can confirm the base station V2 works, and the added slowest-fastest speeds on the wave is nice, however it still does not seem to support the Nommo Chroma speakers I have.

Screen Shot 2021-02-16 at 8 54 11 AM

**Comment by dhobi** [comment]
As far as I remember, razer-macos only supports maximally one device of one type (=keyboard, mouse, mat, headphone, accessory). You could quickly check this by unpluggin the Razer Base Station V2 Chroma. The Nommo Chroma should appear in the menu then. Correct?

**Comment by sourav-dey** [comment]
Doesn't look like it supports nommo pro too. I have a keyboard, mouse and the speakers, so its one of each kind.

**Comment by billstevenson** [comment]
I was able to verify the Base Station V2 works. Thanks!

I also have a mouse pad arriving today that sounds like it will work. I will report back on that. 

In addition, I got the Mouse Bungee Chroma, which does not appear to be recognized. Is that because it is competing with the Base Station V2 Chroma for accessory class, or something else?

**Comment by billstevenson** [comment]
> On Feb 16, 2021, at 12:02 PM, Bill Stevenson <bill@billstevenson.org> wrote:
> 
> I was able to verify the Base Station V2 works. Thanks!
> 
> I also have a mouse pad arriving today that sounds like it will work. I will report back on that. 
> 
> In addition, I got the Mouse Bungee Chroma, which does not appear to be recognized. Is that because it is competing with the Base Station V2 Chroma for accessory class, or something else?

It looks like unplugging the Base Station V2 Chroma does not affect the outcome for the Mouse Bungee, so it is not a contention issue. So, I presume we need support for the device to land upstream in openrazer. Correct?

The Mouse Bungee device doesn’t seem particularly different in complexity from the Base Station, though perhaps it has a different number of LEDs which would inform the animations. 

>

**Comment by billstevenson** [comment]
I was able to verify that my Firefly Mouse Mat V2 works fine in this latest update, FWIW. I don't know if it worked before, though, I only got it today.

So, in summary, the only accessory that is listed as working in openrazer that doesn't seem to be working in the latest update is the Mouse Bungee Chroma.

Let me know how I might help with that.

**Comment by dhobi** [comment]
> So, in summary, the only accessory that is listed as working in openrazer that doesn't seem to be working in the latest update is the Mouse Bungee Chroma.

New PR which should fix the detection of other accessories than the base station v2 chroma: 
#256 - v0.3.6 doesn't support razer nommo pro.

**Comment by Lathanwalker** [comment]
> As far as I remember, razer-macos only supports one device of one type (=keyboard, mouse, mat, headphone, accessory) at max. You could quickly check this by unpluggin the Razer Base Station V2 Chroma. The Nommo Chroma should appear in the menu then. Correct?

Ahh yes you are correct, my bad! I set the configuration for my base station then unplugged it and it recognized the Nommo Chroma. Thank you

**Pull request merged**
