### PR TITLE
Adding state manager

### LINKED ISSUE #122: [Feature Request] Option to turnoff light when screen saver is active
Hi there,

First of all, I can't thank you enough for this application, really! 🙏🏻

One thing that I would love to have is the option to turn off the keyboard lights whenever the screensaver is activated or the screen goes to sleep.

Thanks in advance and keep up with the amazing job.

### LINKED ISSUE #207: Razer-macOS does not remember settings from previous launch
If I quit Razer MacOS, and relaunch, it does not reset the colors for the keyboard. Since the keyboard may have been plugged into a different computer, it is important that it is able to do this. Instead, you do need to go back in and reset every setting for each computer. 

Version: 0.3.4
Keyboard: Razer Blackwidow Chroma
Mouse: Razer Abyssus V2
OS: Catalina 10.15.7

### PR DESCRIPTION
**Pull request by dhobi**
- Allows to create unique states for all the devices
- Allows to use those states on application / system events

This could fix #207, fix #122 and be an enhancement for #206

This is still in a alpha / beta state (untested behavior when certain devices are removed in between state switches).

### CODE REVIEW

**Comment by dhobi** [comment]
Some preview images how it could look like:

image

image

**Comment by dhobi** [comment]
I'm thinking about adding all the other events of electrons powerMonitor as well to give the end user all the options.

Testing so far looks quite alright. Only thing I'm missing is the "screen goes sleep" event. Could be that's the "lock-screen" event from powerMonitor. I'll update the PR soon 😄

**Comment by dhobi** [comment]
Apart from some labels I think this PR is ready to be merged and released.

**Comment by 1kc** [comment]
Just tested it. Works well!

**Pull request merged**
