### PR TITLE
Universal app bundle support 

### PR DESCRIPTION
**Pull request by sgulls**
Add build script.
fixed iohook issue.

built on x86_64 Big Sur and both x64 and arm64 packages are working.

### CODE REVIEW

**Comment by sgulls** [comment]
upped dev dependency versions and universal binary/app bundle support

**Comment by overcurrent** [comment]
@1kc I'm trying to get universal app bundle working based on the work by @sgulls.

Could you test this (https://a.tmp.ninja/oHnqqiCx.dmg) dmg whether it runs on your Intel Mac or not?

**Comment by 1kc** [comment]
I will try this tonight in my time zone

**Comment by 1kc** [comment]
> @1kc I'm trying to get universal app bundle working based on the work by @sgulls.
> 
> Could you test this (https://a.tmp.ninja/oHnqqiCx.dmg) dmg whether it runs on your Intel Mac or not?

Hey @overcurrent, Ive just tried it on my intel Mac, the frontend works but unfortunately the backend drivers doesn't. I am suspecting binding.gyp isn't producing the correct addon.node for the respective architectures.

You can use the following to investigate.
Screen Shot 2021-09-13 at 9 28 58 pm

One solution could be just to build both addon_arm.node and addon_x86.node and then get the frontend to call the right one?

**Comment by overcurrent** [comment]
> > @1kc I'm trying to get universal app bundle working based on the work by @sgulls.
> > Could you test this (https://a.tmp.ninja/oHnqqiCx.dmg) dmg whether it runs on your Intel Mac or not?
> 
> Hey @overcurrent, Ive just tried it on my intel Mac, the frontend works but unfortunately the backend drivers doesn't. I am suspecting binding.gyp isn't producing the correct addon.node for the respective architectures.
> 
> You can use the following to investigate.
> Screen Shot 2021-09-13 at 9 28 58 pm
> 
> One solution could be just to build both addon_arm.node and addon_x86.node and then get the frontend to call the right one?

OK, thanks for the feedback. I'll need to investigate this more later.

In the meantime, I tried fixing the cross-compilation issue and test packages are here: https://github.com/overcurrent/razer-macos/releases/tag/v0.4.5-fix-cross-compilation

I tried the Intel version using Rosetta translation layer and it runs for me now. It would result in the same Javascript error as before without the changes made to the binding.gyp file.

Let me know if the Intel package also runs natively on your Mac and I will create pull request to fix cross compilation for upstream master.

**Comment by sgulls** [comment]
sorry got caught up with school and stuff but I will try to start working on this again

Also, slightly off topic to this PR but do you think you could implement a way to take the output of a [USB dump](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) of the RGB data Razer Synapse 3 sends over USB?

**Pull request closed without merging**
