### PR TITLE
Show all devices

### PR DESCRIPTION
**Pull request by 1kc**

### CODE REVIEW

**Comment by 1kc** [comment]
@dhobi seems to be working well! Let me know when you think its ready to merge. Using json to map devices to types is great!
One thing I'd like to add is how would a contributor go about adding new devices.

A main goal of this project from the start was to make it as easy as possible to port devices over from openrazer. As a result , it is very close to their codebase. Just wondering how this would be impacted as the result of the refactor. 
If you could describe it to me or add the brief process it in the wiki/readme that would be awesome.

**Comment by dhobi** [comment]
I have just added the Cycle Animation color picker again and I think that the branch is now "feature complete" (as in: it should be able to do the same stuff as before).

I agree that the documentation should be updated. The main thing which has changed is that instead of returning the device name (C code) a json file has to be added.

To sum up, I currently see these open points:
- documentation update
- order of the devices in the menu
- fill up image and features properties in the device json files

**Comment by dhobi** [comment]
I couldn't resist refactoring the "device features" and changed the view(s) a bit as well.
This got waaaay bigger than I initially anticipated, sorry.

Only point left now is the documentation. Should this go into the wiki?

**Comment by 1kc** [comment]
That's awesome Daniel, I will check it out.
Good to have an experience engineer to look at it. 🙂

I've added you as a collaborator so you can add it the wiki.
Actually, I think putting it in the README would be accessible to the contributors?




________________________________

**Comment by dhobi** [comment]
I think we can merge this now. 

Please check it first if those GUI changes are still ok with you and feel free to change and/or revert stuff.

It was quite some back and forth sometimes but I think this way it is now is the cleanest (separation of view and models).

I'll add some documentation in the wiki as soon as the merge is through.

**Comment by 1kc** [comment]
Awesome! I’ll have a look Friday and Saturday

**Comment by 1kc** [comment]
I am having trouble building it. 

When running the built .app
Screen Shot 2021-03-07 at 10 32 16 pm

Any ideas why?

**Comment by dhobi** [comment]
Hmm maybe my approach of copying the device json files by the webpack copy plugin is bad as it looks like that it is looking at the wrong location/folder for the device json files. 
Maybe I should switch to something like require.context and remove the copy plugin?

**Comment by dhobi** [comment]
I'll check the commited fix at home (I don't have a mac here). Sorry about the hassle.

**Comment by dhobi** [comment]
I was able to test the build (yarn dist, had to comment the arm build though). Please retest. Works for me™

**Comment by 1kc** [comment]
Awesome thanks Daniel, will have a look soon. I had to comment out the arm too before.

**Comment by 1kc** [comment]
Looks very good @dhobi. Definitely has a polychromatic and Synapse feel to it now. 
Everything works and I can see a lot of sensible refactors 😁.
One thing I will change is making the window a bit wider and shorter. See screenshots
Before:
Screen Shot 2021-03-08 at 10 12 16 am
After:
Screen Shot 2021-03-08 at 10 13 02 am

Will merge for now. Let me know your thoughts and Ill release it.

**Comment by dhobi** [comment]
Sure, feel free to adapt / change. I just made the body scrollable in height as the mouse devices have a bit of more options as the keyboard and the window is not resizable when in "production" mode.

**Comment by 1kc** [comment]
Hey @dhobi, finally merged it and released it! 🎉 🥳When you get the chance, do you mind adding some of the major new features you've added to README? I'll update the Release Notes to reflect this as well.

**Pull request merged**
