### PR TITLE
Added support for Razer Mamba TE

### PR DESCRIPTION
**Pull request by BruskB**
Added support for Razer Mamba TE.

### CODE REVIEW

**Comment by 1kc** [comment]
Could you confirm this works with a physical device @BruskB? Cheers!

**Comment by robli298** [comment]
I have tried to compile the project using the new changes from this pull request and there some compile errors on this file:

- line 624 wrong syntax "**case case** USB_DEVICE_ID_RAZER_MAMBA_TE_WIRED**::**"
- line 852 and 857, the cases are duplicated we have two times the USB_DEVICE_ID_RAZER_MAMBA_ELITE

**Comment by BruskB** [comment]
Hello, sorry for late response. I am having a busy week, I will look at the errors and work on them.

**Comment by joxy88** [comment]
Can you add support for the firefly V2. would appreciate it

**Comment by BruskB** [comment]
There must be no errors left right now. @1kc can you compile a test release when you are available?

**Comment by 1kc** [comment]
@robli298 please give this one a go: https://github.com/1kc/razer-macos/releases/tag/v0.2.8-testing

**Comment by robli298** [comment]
@1kc it seems not working on Big Sur 11.0.1 (20B29). I gave a try and same as before, the device is been recognised but no action can be applied.

**Comment by BruskB** [comment]
I will look further through it, I can close the request in the mean time if needed

**Comment by amaldonadoest** [comment]
I have Big Sur and not it's not working for me.

**Comment by BruskB** [comment]
Was not possible to finish the project.
I'll be looking into it whenever I have time, I'll close the pull request for the moment.

**Pull request closed without merging**
