### PR TITLE
Added support for Razer Ornata V2

### PR DESCRIPTION
**Pull request by Bennu91**
Tested on my own keyboard, works fine.

### CODE REVIEW

**Comment by expremo** [comment]
how can I get a DMG file for installing this? I guess I need to wait for the merge, right?

**Comment by sourav-dey** [comment]
On your branch run yarn dist and that will generate the dmg file.

**Comment by Bennu91** [comment]
Let me know if it works for you too. @1kc can i share the compiled app with @expremo ?

**Comment by adjamalbek** [comment]
Can you please share your dmg file. Since latest release doesn't include your commit. 
Greatly appreciated

**Comment by 1kc** [comment]
Sorry guys I am a bit busy during this week, I will look over it and merge it over the weekend to make a release.

**Comment by adjamalbek** [comment]
Thank you a lot! Will be waiting for that release

**Comment by Bennu91** [comment]
Btw sorry for the mess i did with all this commits 😜

**Comment by 1kc** [comment]
All good haha thanks for the contirbution

**Comment by aheze** [comment]
@Bennu91 Thank you so much! I just got my Ornata V2 a couple weeks ago.

**Pull request merged**
