### PR TITLE
Add support for Razer BlackWidow V3 Pro (Wired)

### PR DESCRIPTION
**Pull request by ryan-idea42**

### CODE REVIEW

**Comment by ryan-idea42** [comment]
@1kc This is the update... I copied the BlackWidow V3 TK configuration, since in the openrazer project, it seemed to be a lot like that... Please let me know if you see any changes that need to be made.

**Comment by 1kc** [comment]
Does it work well with your own device? Since I don't have the keyboard, I could make a release and let others have a go as well.

**Comment by ryan-idea42** [comment]
Doesn't look like Ripple works. Maybe not supported by this keyboard? Any way to disable this effect for this keyboard configuration? 

Aside from that, all other options work.

**Comment by ryan-idea42** [comment]
@1kc I'm dumb. Figured out how, just remove from configurations!!! LOL

Also updated the wheel configuration so the full keyboard lights are used.

**Comment by 1kc** [comment]
All clear to merge @ryan-idea42 ? I will compile and make a release!

**Comment by ryan-idea42** [comment]
@1kc I think we are clear, at least for the wired configuration. :-) 

Thank you! Love what you're doing here. You don't know how disappointed I was to realize there was no Synapse 3 support for these keyboards on Mac. Glad I stumbled on to this and that I could put my HS C++ skills to good use. :-D

**Comment by 1kc** [comment]
@ryan-idea42 Cheers and thanks for the contribution! Since I don't have all the Razer devices, I am mainly relying on developers like youself with Razer devices to move this project forward.

**Pull request merged**
