### PR TITLE
Fix Basilisk V3 and Huntsman V2 Analog

### LINKED ISSUE #609: Basilisk V3 cannot enable underneath LEDs if turned off in Windows
The Basilisk V3 has a layer of LEDs under the mouse.

Razer macOS can control LEDs only in the default / 1st on-board memory profile.

I have a macOS profile with custom macros which I activate in Windows before plugging the mouse into macOS, so that Synapse 3 copies the profile into the 1st on-board memory profile. This profile also has brightness disabled because I want this to be the default in macOS unless I specifically set a color effect.

Razer macOS allows me to enable the brightness only for the scroll wheel and logo. There is no way to enable the brightness for the LEDs under the mouse. If the brightness is already enabled in Windows, Razer macOS can control the colour of bottom LEDs.

### PR DESCRIPTION
**Pull request by WrathofthePast**
I copied openrazer when they added support, but they had the wrong number of rows. They later corrected it too.

### CODE REVIEW

**Comment by WrathofthePast** [comment]
For the Basilisk V3 this fixes:
- Error in razermouse_driver.c
- Missing additions to .gitignore from #463

**Comment by WrathofthePast** [comment]
May fix #609

**Review by dhobi — APPROVED** [review]
LGTM

**Comment by MrUltimate** [comment]
Hey folks, just a heads up that the V3 (in my case, the V3 Pro) doesn't show up at all in the device list!

**Pull request merged**
