### PR TITLE
Recognizing Razer Basilisk Ultimate and its charging docker

### PR DESCRIPTION
**Pull request by sourav-dey**
Recognizing Razer Basilisk Ultimate and its charging docker

### CODE REVIEW

**Comment by 1kc** [comment]
This is great, thanks for adding this. Since I don't have a Razer mouse or dock, its very hard for me to add and test it. Let me know when its ready to merge.

**Comment by 1kc** [comment]
Also thanks for making the spaces in the switch statements consistent. Have been meaning to do that.

**Comment by sourav-dey** [comment]
No problem :)
It is ready to merge. It detects my Razer Basilisk mouse and I can change colors and patterns.

**Comment by sebmck** [comment]
I also have a Basilisk Ultimate, however testing your branch it only changes the Razer logo color and not any of the other lights. Not sure if there's just something whacky though with my mouse since I alternate between corded and dock usage.

**Comment by sourav-dey** [comment]
Ya, it looks same to me as well. The snake part is changing. I didn't check the mouse wheel part. 

Also, it looks like a common problem. https://github.com/1kc/razer-macos/issues/31 - Same issue with DeathAdder.

Let me take a stab at it. Atleast this code change will recognize Basilisk Ultimate and change color to the snake part.

**Comment by 1kc** [comment]
The scroll wheel LED colour change hasn't actually been implemented. See this [function](https://github.com/openrazer/openrazer/blob/6c71ccfc2bbecc014bb13dd301b2b703ef75fcfa/driver/razermouse_driver.c#L1921) from upstream openrazer. Let me know how you go.

**Comment by sebmck** [comment]
Ahhh that makes sense. Thanks for the extra context! Thanks @sourav-dey for adding support for what you could!

**Comment by sourav-dey** [comment]
@sebmck I fixed the wheel and left and right side lights too.
Please do test once and let me know. Works fine with mine.

**Comment by sourav-dey** [comment]
Also the latest changes will technically fix https://github.com/1kc/razer-macos/issues/31 issue too.

**Comment by sourav-dey** [comment]
Actually the fix is just for wave now. I am adding it for other patterns too.

**Comment by sourav-dey** [comment]
Fixed that.

**Comment by 1kc** [comment]
Good work! Will merge once someone else can confirm it is working.

**Comment by sebmck** [comment]
Woah, awesome! Can confirm it works! All lights are updating properly. Thank you both for your work. I bought a Huntsman Elite and Basilisk Ultimate and was pretty bummed when I found out how awful anything Razer on macOS is.

**Comment by 1kc** [comment]
Thanks for testing Sebastian! I will create a new release with those updates by @sourav-dey. :)

**Pull request merged**
