### PR TITLE
Wave speed control added for Keyboards

### PR DESCRIPTION
**Pull request by akaler**
I saw an issue #130 and I fixed it. It only works on these following keyboards
RAZER_ORNATA
RAZER_ORNATA_CHROMA
RAZER_ORNATA_V2
RAZER_HUNTSMAN_ELITE
RAZER_HUNTSMAN_TE
RAZER_BLACKWIDOW_2019
RAZER_HUNTSMAN
RAZER_BLACKWIDOW_ESSENTIAL
RAZER_CYNOSA_CHROMA
RAZER_TARTARUS_V2
RAZER_BLACKWIDOW_ELITE
RAZER_CYNOSA_V2

I did so by adding a speed parameter to razer_attr_write_mode_wave functions and any other required changes

### CODE REVIEW

**Comment by 1kc** [comment]
Also works on my regular Huntsman. Love this implementation!

**Comment by OnlyReFLeX** [comment]
It's still fast for me =(

**Comment by 1kc** [comment]
I am making a release right now haha.
Give me 30 minutes.
It will be v0.3.3

On 28 Dec 2020, at 8:39 pm, Osman Baliev <notifications@github.com> wrote:

﻿

It's still fast for me =(

**Comment by 1kc** [comment]
@OnlyReFLeX  try https://github.com/1kc/razer-macos/releases/tag/v0.3.3

**Comment by OnlyReFLeX** [comment]
slower please :DD it's still fast (slowest it's not slowest))

**Comment by akaler** [comment]
@OnlyReFLeX I can add a turtle speed mode, if you want

**Comment by OnlyReFLeX** [comment]
@akaler It will be wonderful :3

**Pull request merged**
