### PR TITLE
add wheel effect

### LINKED ISSUE #325: Wheel Effect
i feel like the wheel effect would be a great addition to the software. It was requested a while back (#57) but was never addressed. thanks for all your hard work towards this project :)

### PR DESCRIPTION
**Pull request by stevenliuyi**
Add wheel effect to resolve #325

### CODE REVIEW

**Comment by dhobi** [comment]
Wow, works great and looks so cool!! 👍 

I really regret that I put the col/row properties in the feature config and not to the device itself. It would have saved you some work/time I guess. I'm sorry about this.
I'll happily clean that after we merge your PR.

**Comment by 1kc** [comment]
Apologies for the delay guys. Will merge and release!

**Comment by 1kc** [comment]
Screen Shot 2021-04-07 at 1 13 30 am
I might change this to make it just say 'disabled', since it does extend the menu width by quite a bit.

**Comment by 1kc** [comment]
Is there a reason for keyboards having 'wheel' effects @stevenliuyi?. (https://github.com/stevenliuyi/razer-macos/blob/296abf2e350d798954e4ef43da38709b1bb114bc/src/devices/huntsman_elite.json)

It shows up as an option for my keyboard but its greyed out with 'Wheel (missing rows, col config)'

Will release for now though.

**Comment by Sharptail** [comment]
Ermm, wheel effect not showing up for razer basilisk ultimate?

Screenshot 2021-04-07 at 12 14 08 AM

**Comment by 1kc** [comment]
I've made the latest release a 'pre-release'. Not exactly sure how to fix it until I have clarification from the others.

**Comment by avigucci** [comment]
It works for me

**Comment by 1kc** [comment]
> It works for me

I couldn't see you screenshot could you please reupload or let me know what device it was? Thanks

**Comment by avigucci** [comment]
It is a Blackwidow Elite
Screen Shot 2021-04-06 at 5 48 23 PM

**Comment by 1kc** [comment]
My bad 🤦. I thought wheel effect was for mice, makes sense now

**Comment by stevenliuyi** [comment]
> My bad 🤦. I thought wheel effect was for mice, makes sense now

Yes, it's only for keyboards.

A side note: I don't have a Windows PC right now, so I can't use Synapse 3 to set the official wheel effect on my keyboard. My implementation is just based on the official Youtube video (https://www.youtube.com/watch?v=KGURYdPXJe4), so it may well not be a very accurate replica.

**Comment by stevenliuyi** [comment]
> Is there a reason for keyboards having 'wheel' effects @stevenliuyi?. (https://github.com/stevenliuyi/razer-macos/blob/296abf2e350d798954e4ef43da38709b1bb114bc/src/devices/huntsman_elite.json)
> 
> It shows up as an option for my keyboard but its greyed out with 'Wheel (missing rows, col config)'
> 
> Will release for now though.

Do you still have the wheel effect greyed out with Huntsman Elite? It seems weird since the configuration is already added on https://github.com/1kc/razer-macos/blob/master/src/devices/huntsman_elite.json

**Comment by stevenliuyi** [comment]
> > Is there a reason for keyboards having 'wheel' effects @stevenliuyi?. (https://github.com/stevenliuyi/razer-macos/blob/296abf2e350d798954e4ef43da38709b1bb114bc/src/devices/huntsman_elite.json)
> > It shows up as an option for my keyboard but its greyed out with 'Wheel (missing rows, col config)'
> > Will release for now though.
> 
> Do you still have the wheel effect greyed out with Huntsman Elite? It seems weird since the configuration is already added on https://github.com/1kc/razer-macos/blob/master/src/devices/huntsman_elite.json

Actually, I just found out the issue. I'll fix it soon.

**Comment by 1kc** [comment]
Sounds good @stevenliuyi. I think this one might be related also #342

**Comment by avigucci** [comment]
The colouration is slightly off in one corner (pink is too light). The wheel effect follows the same colours as the wave effect but in a circular pattern if that helps. Also, the speed feature is now glitched and the wheel is frozen at a specific pattern - which is good so I can take a picture and show you the colouration.
IMG_1944

**Comment by stevenliuyi** [comment]
> Sounds good @stevenliuyi. I think this one might be related also #342

It should be fixed by #343

**Comment by 1kc** [comment]
> > Sounds good @stevenliuyi. I think this one might be related also #342
> 
> It should be fixed by #343

That PR #343 doen't include any changes for Blackwidow V3, you think it will still fix it?

**Comment by stevenliuyi** [comment]
> > > Sounds good @stevenliuyi. I think this one might be related also #342
> > 
> > 
> > It should be fixed by #343
> 
> That PR #343 doen't include any changes for Blackwidow V3, you think it will still fix it?

It seems that the configuration for Blackwidow V3 has been missing since the last release. I just added the configuration, so it should be good now.

**Comment by 1kc** [comment]
Ah cheers @stevenliuyi, I will release it now.

**Comment by stevenliuyi** [comment]
@avigucci 
https://github.com/1kc/razer-macos/blob/bfa3a419eb0c1692a8f894497f12e4fbccb7f284/src/main/animation/animationwheel.js#L39

Right now the saturation is set to be 70%. I think increasing the saturation should help. Maybe someone can test to see what would be the best value that matches the official effect? Perhaps it should be just 100%?

**Comment by 1kc** [comment]
Just tested it on my huntsman, it works and is indeed very cool!

**Comment by avigucci** [comment]
@1kc 
Epic, hopefully, we'll see it in the next update. Thanks again!  :)

**Pull request merged**
