### PR TITLE
Adding mouse battery level and charging status

### PR DESCRIPTION
**Pull request by sourav-dey**
Now, it shows mouse charge level and whether its charging or not.

IMG_9167
IMG_9166

Also, this needs to be tested with Wired only mouse, as I don't know what info it will give.

### CODE REVIEW

**Comment by 1kc** [comment]
This looks very nice! Does it only work with the Razer Basilik or are all wireless mice supported?

**Comment by sourav-dey** [comment]
It should work with all wireless mice. 
Someone needs to test with wired only mouse once to see if it just shows the mouse name and no charge part.
I don't have a wired razer mouse.

**Comment by 1kc** [comment]
I've got a wired mouse. This is what it shows for me.
Screen Shot 2020-07-30 at 1 01 56 pm

**Comment by sourav-dey** [comment]
Oh ok. I will fix that, so for wired only mouse it should just show the mouse name as charging is not applicable in such case.

**Comment by sourav-dey** [comment]
Should be fixed. Please do test again when you get a chance.

**Comment by 1kc** [comment]
👍 works correctly now. Will merge,
Screen Shot 2020-07-30 at 1 40 57 pm

**Pull request merged**
